global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.royalhenryking.com']

  - job_name: 'your-application'
    static_configs:
      - targets: ['prod.royalhenryking.com']
